language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: JKI7UjkSBSPQ6a/v7EQE9QxK9Q8OPBtr/Wof1I+I4P0/JySOjiQHmJyiixYGMwYCg35KQ1j/RwaRXQmPUC25EZpHzw4ffDDxiT6ynLw1/h6e+yhllVtbn8NoVKJc9I4KhPBS/3CBEtlLhXogstT7I8WMXmNnEYo4hnMcL/N+D54mZHwFu/V3XFU/nZqIbEfi9x/9zQ1YUheOMpKnUshNdawTFTuc9PAt/aqdDVLDQD5RtLrsRcOdRWrkK072KKR8c4dc2NVZ/0SK0HfG5JiUntc8FfbqryrEqSnkLXPpWO7oziWxihqx2zE1U0kbQXZkjojmVmiuOsqdDT4OWCZeBifUmDwCuKubgQ9bB1hYZ6AvSzTIez+TSAbPZK8u+gSC8d4YBb3o5VbVSkcKDg/VrqUrpKDXDNBA0HbkFiZQiM4zWPXX7GgzxZjyFq3j/4bJ7sN1w8GvY6ombsYAzDMRMpZHGPqHEVhywqCXhChesS48O5/R23TOHK1VV6ofj1VwABu8l0Rwz1tYg1Bu6u7s+/yIg52pVj/DOVMmh4/k6QWcFf8VP1hWBEDFSvE6zSo98spARNEy9hTL+k+XlXgrmUXztqh0kF52I60uBQWw351o9SaQBFMR2312JiuoDxABnSqxcOXgKPc+BAS0Ppw6DTSS9uNBT08uWDebtoHWbh4=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
