language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: G9/yDnhCMnp9yO59PKuSGP5t1fBfTU0l4mlcfhn52wvUGxGB7QGi2nOpW7FQRGTG0/JlA/2c4tQSzzCEKdEJumOck9M9LGGoMPJ/fqKNlK0QugDeEmtJgXpKwWZ4p3ZHIUBbctXZSz1YWCgeuzFH/VfagJwTYeO8X8su5swfo3s3Q+tkuLO5MptaM5tKMe0p8hY6GybSPZLZXPRF5MPYg3jXkuNNkeSe2sS+GoukPjQaE4Zrfep2d1YeiPMTV1BpQCJuKQFbb1g6dupJTgGgBbPRvgC3yHrBhJ5WT2qlalilt/jHTt3SnxJrhhX3ASBksCP+zbC6OPNUg5LlxSbC+ZyE/ynH+dG60FC5KCRzb467QeL40p/pXS0wJ2PihnSs4gDj/93v9voGakhdbrsrd/oYgHH5oP0jv2GduZB6lybXrsWlxZAUAv0HfkeG8Bu/nP7ZCVABmitQFp8Lj5omz0fmHiUH5IparpLJs1i1SqYOQct6TXEQnTrvhnOEgySY1ebQL3V/30I010DbKMdn4Dw56cJMS3GfKhAVYvRrPlQtMrnNLJVIk6fUFtCHO8kMAuaiXqwgUAzSbM8GRpHAVWFTYSaHOywpf7QK+VnnVkgfCHsEQXMN0WArth/IQUf1z6yVKGFdhoVzQmphO9qyRxwT3J09AdhTqrbQaJBO4L4=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
